<?php

namespace Esupl\Loyverse\Resources;

/**
 * Class Receipt
 *
 * @package Esupl\Loyverse\Resources
 */
class Receipt extends Resource
{
    /**
     * The internal identifier for the receipt. It is unique.
     *
     * @var string
     */
    public string $receiptNumber;

    /**
     * The receipt's note
     *
     * @var string
     */
    public string $note;

    /**
     * The type of the receipt.
     *
     * Enum: "SALE" "REFUND"
     *
     * @var string
     */
    public string $receiptType;

    /**
     * The number of a different sales receipt that is associated with this refund (only for refund receipts).
     *
     * @var string|null
     */
    public ?string $refundFor = null;

    /**
     * The order name or number associated with this receipt.
     *
     * @var string
     */
    public string $order;

    /**
     * The autogenerated date and time when the receipt was created in Loyverse.
     *
     * @var string
     */
    public string $createdAt;

    /**
     * By default, it matches the created_at value.
     *
     * You can set receipt_date to the value that is equal to the date
     * and time in the past when the receipt was created in another system.
     *
     * @var string
     */
    public string $receiptDate;

    /**
     * The date and time when the receipt was updated.
     *
     * @var string
     */
    public string $updatedAt;

    /**
     * The time when this receipt was cancelled.
     *
     * @var string
     */
    public string $cancelledAt;

    /**
     * The name of the the source this receipt comes from.
     *
     * By default it is the name of the application that created the receipt.
     * For receipts created from Loyverse mobile point of sale application the value is "point of sale".
     *
     * @var string
     */
    public string $source;

    /**
     * The total money amount paid by customer (or returned to customer in case of refund).
     *
     * The value includes discounts, taxes, surcharges and tips. The money amount format depends on country
     * of account registration (for example for Japan there is no decimals in money amounts).
     *
     * @var float
     */
    public float $totalMoney;

    /**
     * The total amount of all taxes (VAT and sales tax) applied in the receipt.
     *
     * @var float
     */
    public float $totalTax;

    /**
     * The total amount of points added to customer's points balance.
     *
     * @var float
     */
    public float $pointsEarned;

    /**
     * The total amount of points deducted from customer's points balance (in case of refund).
     * The value is always positive.
     *
     * @var float
     */
    public float $pointsDeducted;

    /**
     * The customer's points balance after transaction.
     *
     * @var float
     */
    public float $pointsBalance;

    /**
     * The customer id associated with the receipt.
     *
     * @var string
     */
    public string $customerId;

    /**
     * The total amount of all discounts applied in the receipt (including discount by points).
     * The value is always positive.
     *
     * @var float
     */
    public float $totalDiscount;

    /**
     * The employee id associated with the receipt.
     *
     * @var string
     */
    public string $employeeId;

    /**
     * The store id where the receipt was paid.
     *
     * @var string
     */
    public string $storeId;

    /**
     * The POS id where the receipt was paid.
     *
     * @var string
     */
    public string $posDeviceId;

    /**
     * The dining option selected for the receipt.
     *
     * @var string
     */
    public string $diningOption;

    /**
     * The list of discounts and it's amounts applied to the receipt.
     *
     * @var array
     */
    public array $totalDiscounts = [];

    /**
     * An array of tax line objects.
     *
     * @var array
     */
    public array $totalTaxes = [];

    /**
     * The total tip money amount for the receipt.
     *
     * @var int
     */
    public int $tip;

    /**
     * The total surcharge money amount for the receipt.
     *
     * @var int
     */
    public int $surcharge;

    /**
     * The line items included in the receipt.
     *
     * @var array
     */
    public array $lineItems = [];

    /**
     * The list of receipt payments.
     *
     * @var array
     */
    public array $payments = [];
}
